[package]
name = "process-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
csv = "1.3.0"
kdam = "0.5.2"
rand = "0.8.5"
